# Generated by Django 5.2.7 on 2025-10-12 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата платежа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма оплаты')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод на счет')], default='transfer', max_length=10, verbose_name='Способ оплаты')),
                ('stripe_product_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID продукта в Stripe')),
                ('stripe_price_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID цены в Stripe')),
                ('stripe_session_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID сессии в Stripe')),
                ('stripe_payment_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на оплату в Stripe')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='materials.course', verbose_name='Оплаченный курс')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='materials.lesson', verbose_name='Оплаченный урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-payment_date'],
            },
        ),
    ]
