# Generated by Django 5.2.7 on 2025-11-10 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_course_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['id'], 'permissions': [('can_edit_course', 'Can edit course')], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['id'], 'permissions': [('can_edit_lesson', 'Can edit lesson')], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
